# We need to fix deployment and macOS now.
osx_image: xcode8.2

os:
  - osx

language: node_js

node_js:
  - "7.4.0"
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
  yarn: true

script:
  - yarn generate-lock-entry
  - yarn dist -- --mac pkg dmg
# Testing doesn't work properly rn.
#  - yarn test
  - node deploy.js

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  - deploy
