osx_image: xcode8.1
 
sudo: required
dist: trusty

os:
  - linux
  - osx
 
language: node_js
 
node_js:
  - "node"
 
cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
  yarn: true
 
addons:
  apt:
    packages:
      - rpm
      - graphicsmagick
      - icnsutils
      - xz-utils

script:
  - test "$TRAVIS_OS_NAME" == "osx" && (yarn dist -- --mac dmg) || (exit 0)
  - test "$TRAVIS_OS_NAME" == "linux" && (yarn dist -- --linux deb rpm) || (exit 0)
 
branches:
  only:
  - master
