language: node_js

node_js:
  - "node"
  
 matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.1

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache
  yarn: true

addons:
  apt:
    packages:
      - rpm
      - graphicsmagick
      - icnsutils
      - xz-util

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist -- --mac dmg
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist -- --linux deb rpm

branches:
  only:
    - master
