# We need to fix deployment and macOS now.
osx_image: xcode8.2

os:
  - osx

language: node_js

node_js:
  - "7.4.0"
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
  yarn: true

script:
  - yarn generate-lock-entry
  - yarn dist -- --mac pkg dmg
# Testing doesn't work properly rn.
#  - yarn test

branches:
  only:
  - master
  - /^greenkeeper/.*$/

#deploy:
#  provider: s3
#  access_key_id: ''
#  secret_access_key: ''
#  bucket: sansari-home
#  skip_cleanup: true
#  region: ap-south-1
#  local-dir: dist
#  upload-dir: home/ibrahim/decaffeinater-builds/macos
#  on:
    # Change the repo to ibujs/decaffeinater when deploying new releases.
#    repo: ibujs/decaffeinater-nodeploy
