# We need to fix deployment now.
osx_image: xcode8.2

os:
  - osx

language: node_js

node_js:
  - "7.4.0"
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
  yarn: true

script:
  - yarn generate-lock-entry
  - yarn make-dmg
# Testing doesn't work properly rn.
#  - yarn test

branches:
  only:
  - master

#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "S3 Bucket"
#  skip_cleanup: true
#  region: eu-west-1
#  on:
    # Edit the below line to ibujs/decaffeinater to deploy.
#    repo: ibujs/decaf